### ISSUE TITLE
Brief audit of `economics.ride`

### ISSUE THREAD

**Issue by deemru** [waveslands/ride#3]
- LOW: different precision in similar formulas: https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L87 https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L112

- LOW: strange hardcoded constants `2` and `3` for dynamic price at sell and buy respectively

- LOW: the same `RESOURCEPRICEMIN` and `FACTORYMAXWAREHOUSE` for all resources and locations

- LOW: `min` is better then additional `if`: https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L86 https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L109

- LOW: unused functions `subRes` and `addMat`: https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L54 https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L64

- LOW: `j.value()`? https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L150

- MEDIUM: unexpected hardcoded user defined slippage grow: https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L90 https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L115

- MEDIUM: dangerous `else` its better to `throw`: https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L126-L127

**Comment by br0x** [comment]
> * LOW: different precision in similar formulas: https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L87
>    https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L112
Fixed

> * LOW: strange hardcoded constants `2` and `3` for dynamic price at sell and buy respectively
Fixed

> * LOW: the same `RESOURCEPRICEMIN` and `FACTORYMAXWAREHOUSE` for all resources and locations
Intended

> * LOW: `min` is better then additional `if`: https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L86
Tried several different ways but decided current one is the simplest

>    https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L109
The same

> * LOW: unused functions `subRes` and `addMat`: https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L54
>    https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L64
Fixed

> * LOW: `j.value()`? https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L150
Fixed

> * MEDIUM: unexpected hardcoded user defined slippage grow: https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L90
>    https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L115
Hardcoded 99%...101% tolerance considered to be safe

> * MEDIUM: dangerous `else` its better to `throw`: https://github.com/waveslands/ride/blob/f7e1f0f5c69fc39e63cb3a51b1ff34842f262166/economics.ride#L126-L127
Considered to be OK for users who joined early, before backpack development
