### ISSUE TITLE
Brief audit of `wlgold.ride`

### ISSUE THREAD

**Issue by deemru** [waveslands/ride#4]
- [x] LOW: double checking? https://github.com/waveslands/ride/blob/4cf7b76500be852b9e2667ad3709b5c376395408/wlgold.ride#L14 https://github.com/waveslands/ride/blob/4cf7b76500be852b9e2667ad3709b5c376395408/wlands_staking.ride#L813
- [x] LOW: sqrt()? (https://docs.waves.tech/en/ride/functions/built-in-functions/math-functions#sqrt) https://github.com/waveslands/ride/blob/4cf7b76500be852b9e2667ad3709b5c376395408/wlgold.ride#L24
- [x] HIGH: `arbitrageDelay` can be bypassed by `addr1.unstakeLand()` + `addr2.stakeLand()` https://github.com/waveslands/ride/blob/4cf7b76500be852b9e2667ad3709b5c376395408/wlgold.ride#L19-L21
- [x] LOW: unchecked strings https://github.com/waveslands/ride/blob/4cf7b76500be852b9e2667ad3709b5c376395408/wlgold.ride#L96-L99
- [x] MEDIUM: should be an error for an user https://github.com/waveslands/ride/blob/4cf7b76500be852b9e2667ad3709b5c376395408/wlgold.ride#L41 https://github.com/waveslands/ride/blob/4cf7b76500be852b9e2667ad3709b5c376395408/wlgold.ride#L108 https://github.com/waveslands/ride/blob/4cf7b76500be852b9e2667ad3709b5c376395408/wlgold.ride#L143
- [x] LOW: looks strange with `!=` next https://github.com/waveslands/ride/blob/4cf7b76500be852b9e2667ad3709b5c376395408/wlgold.ride#L113-L114 https://github.com/waveslands/ride/blob/4cf7b76500be852b9e2667ad3709b5c376395408/wlgold.ride#L148-L149
- [x] MEDIUM: math looks double calculated, we have 1/6 of `usdtAmt` goes to `profitAmount` then we simply should have `wlgAmount = fraction(usdtAmt - profitAmount, MULT8, wlgPrice)` but we actually have unnecessary `buyPrice`, `deltaFunds` and `reissued` https://github.com/waveslands/ride/blob/4cf7b76500be852b9e2667ad3709b5c376395408/wlgold.ride#L124-L130 same for `burned` which is `wlgAmt` https://github.com/waveslands/ride/blob/4cf7b76500be852b9e2667ad3709b5c376395408/wlgold.ride#L161
- [x] MEDIUM: pretty confusing as we already have the big function `getWlgStats()` which still need correction outside of it https://github.com/waveslands/ride/blob/4cf7b76500be852b9e2667ad3709b5c376395408/wlgold.ride#L122-L124 but https://github.com/waveslands/ride/blob/4cf7b76500be852b9e2667ad3709b5c376395408/wlgold.ride#L155
- [x] MEDIUM: outdated or wrong comment (should be called on every unstake) https://github.com/waveslands/ride/blob/4cf7b76500be852b9e2667ad3709b5c376395408/wlgold.ride#L187
- [x] HIGH: `userAmount` depends on variable `totalPieces` so we can have different numbers if `claimInternal()` was or was not called (in other words we have to call `claimInternal()` for every user on every `totalPieces` change) https://github.com/waveslands/ride/blob/4cf7b76500be852b9e2667ad3709b5c376395408/wlglib.ride#L119-L120

**Comment by br0x** [comment]
fixed

**Comment by br0x** [comment]
Reworked, audit concerns considered
